# Generated by Django 5.1 on 2024-09-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='copyright',
            field=models.CharField(max_length=100, null=True, verbose_name='حق کپی رایت'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='link',
            field=models.CharField(max_length=100, null=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(max_length=100, null=True, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='value_title',
            field=models.CharField(max_length=100, null=True, verbose_name='مفدار نمایشی'),
        ),
    ]
