# Generated by Django 5.1 on 2024-09-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0002_alter_settings_copyright_alter_settings_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='link',
        ),
    ]
