# Generated by Django 5.1 on 2024-09-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0005_services_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='عنوان')),
                ('value', models.CharField(max_length=100, null=True, verbose_name='مقدار')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='ایکون')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
    ]
