# Generated by Django 5.1 on 2024-09-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0006_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, null=True, verbose_name='عنوان')),
                ('image', models.ImageField(null=True, upload_to='images/projects', verbose_name='مقدار')),
                ('value', models.CharField(blank=True, max_length=100, null=True, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'خدمت',
                'verbose_name_plural': 'خدمات',
            },
        ),
    ]
