# Generated by Django 5.1 on 2024-09-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0007_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'گالری', 'verbose_name_plural': 'گالری ها'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(max_length=100, null=True, verbose_name='کتگوری'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(null=True, upload_to='images/projects', verbose_name='عکس'),
        ),
    ]
