# Generated by Django 5.1 on 2024-09-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home_module', '0008_alter_gallery_options_alter_gallery_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('job', models.CharField(max_length=100, verbose_name='پست')),
                ('image', models.ImageField(upload_to='images/staff', verbose_name='عکس')),
                ('description', models.CharField(max_length=100, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمندان',
            },
        ),
    ]
